DROP TABLE IF EXISTS bots;
CREATE TABLE bots
(
    id       SERIAL,
    username VARCHAR UNIQUE
);
CREATE INDEX bot_username ON bots (username);
INSERT INTO bots (username)
-- Top PR mergers
VALUES ('arlac77'),
('simlu'),
('bt-admin'),
('rdxvsrmv'),
('bors'),
('github-auto-merge'),
('istio-testing'),
('hail-hephaestus'),
('alibuild'),
('cmsbuild'),
('tensorflow-copybara'),
('AutorestCI'),
('codeserver-test1'),
('jsru'),
('eltci'),
('atyponci'),
('bors-servo'),
('deploy-code-org'),
('modular-magician'),
('bert-e'),
('cve-team'),
('gdgate'),
('folio-translations'),
('swift-ci'),
('miss-islington'),
('ovh-ux-cds'),
('SiarheiSakharevich'),
('rultor'),
('xuwei-k'),
('donedeal-builduser'),
('OPSTestPPE'),
('trilinos-autotester'),
('skia-flutter-autoroll'),
('phantom-worker2'),
('Normation-Quality-Assistant'),
('atlasBuildBot3'),
('PRB0t'),
('atlasBuildbot2'),
-- Top PR creators
('arlac77'),
('GulajavaMinistudio'),
('MrsFlux'),
('MikhailKasimov'),
('codacy-badger'),
('spring-operator'),
('technote-space'),
('maxice8'),
('JuliaRegistrator'),
('bcoe'),
('brotherlogic'),
('sul-devops-team'),
('dustinvanbuskirk'),
('GeertvanHorrik'),
('kawax'),
('suschizu'),
('monojenkins'),
('Mozilla-GitHub-Standards'),
('core-code'),
-- Commenting Bots 
('BrewTestBot'),
('codecov-io'),
('coveralls'),
('liferay-continuous-integration'),
('CLAassistant'),
('signcla-test-signed-corp'),
('signcla-test-signed-indiv'),
('conda-forge-linter'),
('signcla-test-unsigned'),
('kibanamachine'),
('elasticmachine'),
('codecov-commenter'),
('liferay-continuous-integration'),
('MrsFlux'),
('claassistantio'),
('AmplabJenkins'),
('odoomergebotsacrifice-reviewer'),
('pep8speaks'),
('msftclas'),
('TravisBuddy'),
('rust-highfive'),
('cockroach-teamcity'),
('opbld34'),
('opbld33'),
('opbld30'),
('opbld31'),
('opbld32'),
('robodoo'),
('webteam-app'),
('SparkQA'),
('azuresdkci'),
('artsyit'),
('dnfclas'),
('nuxeojenkins'),
('e2ebd1'),
('e2ebd4'),
('e2ebd3'),
('e2ebd2'),
('centos-ci'),
('chainer-ci'),
('id-jenkins'),
('i-date')
ON CONFLICT DO NOTHING;
INSERT INTO bots (username)
SELECT DISTINCT b.username
FROM (
         -- Look up all Login names, matching predefined patterns
         SELECT a.username
         FROM (
                  SELECT DISTINCT pr_author_login AS username
                  FROM pull_requests
                  UNION
                  SELECT DISTINCT event_initiator_login AS username
                  FROM pull_requests
                  UNION
                  SELECT DISTINCT comment_author_name
                  FROM pull_request_comments
                  UNION
                  SELECT DISTINCT comment_author_name
                  FROM pull_request_review_comments
              ) AS a
         WHERE LOWER(a.username) LIKE '%bot'
            OR LOWER(a.username) LIKE '%robot'
            OR LOWER(a.username) LIKE '%-bot-%'
            OR LOWER(a.username) LIKE '%-robot-%'
            OR LOWER(a.username) LIKE 'bot-%'
            OR LOWER(a.username) LIKE 'robot-%'
            OR LOWER(a.username) LIKE '%[bot]'
         UNION
         -- Look up all logins having a Bot tag
         -- Theoretically this step is unecessary because all Bots should have the 'Bot' type
         -- To make sure nothing gets missed, we decided to include it anyways, since the query
         -- is only executed once.
         SELECT pr_author_login
         FROM pull_requests
         WHERE pr_author_type = 'Bot'
         UNION
         SELECT comment_author_name
         FROM pull_request_review_comments
         WHERE comment_author_type = 'Bot'
         UNION
         SELECT comment_author_name
         FROM pull_request_review_comments
         WHERE comment_author_type = 'Bot'
     ) AS b
ON CONFLICT DO NOTHING;
INSERT INTO bots (username)
VALUES ('dotnet-bot'),
('johnpbloch-bot'),
('bsf-doc-bot'),
('oicr-icgc-prod2'),
('pull[bot]'),
('InwitofitkaBot'),
('nodejs-crowdin'),
('travi-bot'),
('eagletmt-bot'),
('yahoo-bot'),
('homebrew-version-migration-bot'),
('pure-bot[bot]'),
('Richienb'),
('archzfs-bot'),
('tigoctm-usr'),
('adoptopenjdk-github-bot'),
('snyk-bot'),
('sauron-gamma-bot'),
('docker-library-bot'),
('openstax-bot'),
('csl-bot'),
('dontcallmedom-bot'),
('owlbot'),
('Nolanus'),
('isrustfastyet'),
('suse-cf-ci-bot'),
('regro-cf-autotick-bot'),
('rhoggs-bot-test-account'),
('jhipster-bot'),
('renovate-bot'),
('slicerbot'),
('thewca-bot'),
('snyk-bot'),
('wet-boew-bot'),
('funlaburjc'),
('inara5435'),
('thundernest-bot'),
('decidim-bot'),
('limesurvey-translations'),
('electron-bot'),
('fossabot'),
('semantic-release-bot'),
('dotnet-build-bot'),
('qb01-bot'),
('k8s-publishing-bot'),
('resin-io-versionbot[bot]'),
('guardrails[bot]'),
('jufab'),
('pyup-vuln-bot'),
('confs-tech-bot'),
('osrfbuild'),
('Lunokhod-Bot'),
('facebook-circleci-bot'),
('traviscibot'),
('allcontributors[bot]'),
('CrowdinBot'),
('magicbroom'),
('codecov-test'),
('chaiscript-buildbot'),
('ApertiumBot'),
('SiliconChip'),
('jenkins-x-bot'),
('vvv-school-bot'),
('dpb587-ci'),
('raspberrypitranslationsbot'),
('jenkins-x-bot-test'),
('jollygoodbot'),
('getsentry-bot'),
('abf-repo-bot'),
('garybot2'),
('OCA-git-bot'),
('netkan-bot'),
('cstbuilds'),
('tweakCompatible-bot'),
('bot50'),
('njgingrich-bot'),
('currencybot'),
('raspberrypilearningbot'),
('acomsmpbot'),
('scala-steward'),
('jsdelivrbot'),
('imgbot[bot]'),
('authenticator-bot'),
('istio-testing'),
('javafxports-github-bot'),
('bikesharebot'),
('c9bot'),
('ubo-bot'),
('docusaurus-bot'),
('collab-ui-bot'),
('svc-excavator-bot'),
('softwarefactory-project-zuul[bot]'),
('opentraveldata-bot'),
('lj-team'),
('AutorestCI'),
('dpfrakes-bot'),
('r-ryantm'),
('elife-bot'),
('mumukibot'),
('CssBuildBot'),
('greenkeeperio-bot'),
('jetstack-bot'),
('dotnet-maestro[bot]'),
('yogstation13-bot'),
('tedium-bot'),
('oclif-bot'),
('lokalise-bot'),
('babot'),
('jonasabreu'),
('grid-bot'),
('bot-monkey-1'),
('scala-steward'),
('violinist-bot'),
('phpmyadmin-bot'),
('svip'),
('bitnami-bot'),
('nodebb-misty'),
('st-l10n-bot'),
('dotnet-bot'),
('haxe-ci'),
('ophobe-bot'),
('jenkins-nedprod'),
('balloobbot'),
('FlexGet-Bot'),
('davetaz'),
('bactrian'),
('reactjs-translation-bot'),
('spoon-bot'),
('lostanlen-bot'),
('egov-commit-bot'),
('koideploy-commit-bot'),
('sel-bot'),
('spryker-release-bot'),
('genesis5435'),
('yoshi-automation'),
('dependabot[bot]'),
('jx-activiti-cloud'),
('kspckan-crawler'),
('coorpacademybot'),
('violinist-bot'),
('devtube-bot'),
('ejdquotes-bot'),
('vscode-issue-tracker-bot'),
('renovate[bot]'),
('cwl-bot'),
('wppluginsbot'),
('pytorchbot'),
('antag99bot'),
('enginered-bot'),
('bluespice-github-bot'),
('miss-islington'),
('Code-Inside-Bot'),
('snyk-bot'),
('js-org-bot'),
('NgDashboard'),
('doppins-bot'),
('ampproject-artifacts-bot'),
('ForbesLindesay-Bot'),
('making-bot'),
('zeit-github-tester[bot]'),
('hunter-cache-bot'),
('FTL13-Bot'),
('zenossbot'),
('gitbook-bot'),
('tgs-bot-ghost'),
('dune-community-bot'),
('lasp-lang-evaluator'),
('pdfjsbot'),
('yoshi-automation'),
('scala-steward'),
('niveristand-diff-bot'),
('graviteeio'),
('joe-bot'),
('github-learning-lab[bot]'),
('edx-transifex-bot'),
('grid-bot'),
('fabric8-analytics-cve-bot'),
('lektor-bot'),
('okkez-bot'),
('local2-rollout-io[bot]'),
('grommet-github-bot'),
('llvm-beanz'),
('PJBot'),
('koding-bot'),
('rte-bot'),
('ballerina-bot'),
('ParadiseSS13-Bot'),
('reactjs-bot'),
('MakeSchoolBot'),
('staticman-net[bot]'),
('f1jobs-bot'),
('devkitdoc'),
('wso2-jenkins-bot'),
('CNCF-Bot'),
('bors[bot]'),
('poetroid-bot'),
('hubbed'),
('unato'),
('translatewiki'),
('renovate-bot'),
('qubesos-bot'),
('pyup-bot'),
('ninjadotorg-bot'),
('poppy-bot'),
('cheminfo-bot'),
('openstackadmin'),
('dn-wp-bot'),
('depfu[bot]'),
('aur-archive-bot'),
('openmrs-bot'),
('serra-bot'),
('sisyphus-bot'),
('jujubot'),
('HitkoDev'),
('whitesource-bolt-for-github[bot]'),
('smunilla'),
('webuildsg-bot'),
('24emebot'),
('mergify[bot]'),
('BrewTestBot'),
('scrutinizer-test-bot'),
('felixmulder'),
('grass-svn2git'),
('va-bot'),
('nabijaczleweli'),
('jacogr'),
('pxw-bot'),
('element-bot'),
('grommetux'),
('drprofesq'),
('mixpanel-bot'),
('dotnet-maestro-bot'),
('nur-bot'),
('homeassistant'),
('dragon-bot'),
('oll-bot'),
('fabric8-analytics-cve-bot'),
('jhipster-bot'),
('thoth-zuul[bot]'),
('muibot'),
('upload-bot-5n7aq'),
('serenity5435'),
('nba-espn-stats-and-info-bot'),
('openhab-bot'),
('austenmc')
ON CONFLICT DO NOTHING;